import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "/app/header/page.jsx";

const lexend = Lexend({weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className}`}>

        <div className="container">
          <Header />
          {children}
        </div>
        
      </body>
    </html>
  );
}
